### ISSUE TITLE
Security problem 

### ISSUE THREAD

**Issue by idantb101** [FACN3/al-forum#54]
Please notice there is probably an error some where in the code, 
while trying sql injection i was able to crash the website, 
my steps where only injection on login page and direct injection  to the path
https://facn.herokuapp.com/check_user?username=
and this page gives you access to all your posts
https://facn.herokuapp.com/get_posts

**Comment by ghassanmas** [comment]
This page only gives you access if you are logged in : https://facn.herokuapp.com/get_posts
also that page would crash the website if you are not logged in, it will be fixed in the next commit. 

Regarding this https://facn.herokuapp.com/check_user?username= I wasn't able to reproduce the same issue and could you what exactly have you typed to you made sql injection?
